var config = {
    email: 'joel.dice@gmail.com',
    speakers: [ '',
                'Brian Gray',
                'Carl Medearis',
                'Dave Neuhausel',
                'Dave Terpstra',
                'Eric Murrell',
                'Fran Blomberg',
                'Hugh Halter',
                'Jon Gettings',
                'Kathy Escobar',
                'Landon Lynch',
                'Leah Kostamo',
                'Michael Hidalgo',
                'Nick Elio',
                'Paul Young',
                'Ryan Taylor',
                'Amanda Pennington',
                'Serve Global Forum',
                'Scott Oppliger'
              ],
    services: [ '', '9:00', '11:00' ],
    locations: [ 'Uptown', 'Wash Park' ]
};
